### **GEE Models**

Aqui poderão ser visualizados todos os modelos criados. O máximo de modelos é 3, sendo que o botão **ADD** está responsável por adicionar um novo modelo (passando por todas as secções anteriores), cada modelo poderá ser selecionado. Quando o modelo é selecionado este poderá ser editado utilizando o botão **Edit**. O botão **Edit** só estará disponível se apenas um modelo for selecionado. O botão **RUN** permite efetuar a análise *GEE* do modelo ou modelos selecionados, de notar que só será possivel analisar os modelos caso estes estejam selecionados. O utilizador poderá visualizar os resultados da análise *GEE* no menu **Validation & Results** na secção **GEE Results**. Caso pretenda realizar uma validação, utilizando as curvas ROC dos modelos realizados de modo a identificar qual a precisão dos mesmos, após clicar no botão **RUN**, a validação poderá ser realizada no menu **Validation & Results** na secção **ROC Analisys**.
Nota: Após executar o botão **RUN** serão consideradas as variáveis apresentadas nos modelos selecionados, não sendo possível realizar nova edição.
