
#### **GEE MODELS**


**GEE models** (Generalized Estimating Equations), were developed by *Liang and Zeger* [1], these models represent a class of models that are frequently used for data in which there is a correlation between them. These models are an extension of the GLMs (Generalized Linear Models) as they allow analyzing longitudinal data as well as assuming the existing correlation between the data. Unlike other regression models, GEE's do not require a defined data distribution, in turn, they require a data correlation structure to be assigned. The GHG models represent an important tool in the advancement of biomedical research as they allow the analysis of the impact of several variables on individuals singularly over time, as well as on a population, taking into account the observations of each individual [2].










#### **SAGA (Shiny Application for GEE Analysis)**



**SAGA (Shiny Application for GEE Analysis)** is an application with the objective of forming GEE models from a set of data provided by the user, allowing the visualization of its results, graphs and statistics, being possible to validate these same results through ROC analysis. This application allows dynamic use by the user, without prior knowledge of computer programming.
This application allows:
– Build GEE models to different types of variables.
– Describe the model used.
– Identify the relationship of the different parameters with the response variable.
– Generate statistical inferences through confidence intervals and statistical tests, which can be downloaded by the user.
– Graphical complementation in order to facilitate the analysis.









#### References
1. Liang, K.-Y. and Zeger, S. L. (1986). Longitudinal data analysis using generalized linear
models. Biometrika, 73(1):13–22.
2. Wang, Y.-G., Fu, L., and Paul, S. (2022). Analysis of longitudinal data with examples

